server:
  port: 8080
  servlet:
    context-path: /api/innobothealth/
spring:
  data:
    mongodb:
      uri: mongodb+srv://dulangawimalagunasekara:Dulanga1234@sliitproject.9xosu0p.mongodb.net/
      database: InnobotHealth
  mail:
    host: smtp.gmail.com
    port: 587
    username: healthinnobot@gmail.com
    password: cdns hzep rwce mqgu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token:
  signing:
    key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9